# Generated by Django 5.0.7 on 2024-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=True),
        ),
    ]
