# Generated by Django 5.0.7 on 2024-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0011_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
