# Generated by Django 5.0.7 on 2024-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0013_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='online_shop.product'),
        ),
    ]
