# Generated by Django 5.0.7 on 2024-08-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0014_product_related_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
    ]
