# Generated by Django 5.0.7 on 2024-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0015_remove_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
