# Generated by Django 5.0.7 on 2024-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0018_category_slug_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
