# Generated by Django 5.0.7 on 2024-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0020_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
